### PR TITLE
Fix issues for last PR

### PR DESCRIPTION
**Pull request by aceglia**

### CODE REVIEW

**Review by pariterre — APPROVED** [review]
LGTM

**Review by pariterre — APPROVED** [review]
LGTM :)

**Comment by pariterre** [comment]
Ready to merge?

**Comment by aceglia** [comment]
> Ready to merge?

Waiting to add checkerboard floor or other better color than actual.

**Comment by aceglia** [comment]
Ready now!

**Review by pariterre — APPROVED** [review]
LGTM

**Pull request merged**
